"use client";

/**
 * Shared markdown renderer used wherever we display rich text generated by
 * the assistant or stored in saved reports. Centralising the styling here
 * keeps EventDrawer and the saveAnalysisReport preview visually consistent
 * and means future tweaks (spacing, code blocks, link behavior) only need
 * to happen in one place.
 *
 * Notable rules:
 * - `[&_li>p]:my-0` collapses the implicit <p> remark-gfm wraps around list
 *   items in "loose" lists; without it every bullet has an extra blank line
 *   which is what makes raw lists look weirdly stretched.
 * - Nested <ul>/<ol> use `list-[circle]` so hierarchy is visible.
 * - `[&>*+*]:mt-3` provides consistent spacing between top-level blocks
 *   without pulling in @tailwindcss/typography just for prose styles.
 */

import React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { cn } from "@/lib/utils";

const MARKDOWN_COMPONENTS = {
  a: ({ href, children }: { href?: string | null; children?: React.ReactNode }) => (
    <a href={href ?? "#"} target="_blank" rel="noopener noreferrer">
      {children}
    </a>
  ),
  code: ({
    className,
    children,
    ...props
  }: {
    className?: string;
    children?: React.ReactNode;
  } & React.ComponentPropsWithoutRef<"code">) => {
    const isBlock = typeof className === "string" && className.startsWith("language-");
    if (isBlock) {
      return (
        <code className={className} {...props}>
          {children}
        </code>
      );
    }
    return (
      <code className="rounded bg-muted px-1 py-0.5 text-xs font-mono" {...props}>
        {children}
      </code>
    );
  },
  pre: ({ children }: { children?: React.ReactNode }) => (
    <pre className="rounded bg-muted p-3 overflow-x-auto my-2 text-xs font-mono [&>code]:bg-transparent [&>code]:p-0">
      {children}
    </pre>
  ),
};

const BASE_CLASSES = [
  "markdown-body text-sm leading-6 min-w-0 break-words",
  // top-level block spacing
  "[&>*+*]:mt-3",
  // links
  "[&_a]:text-primary [&_a]:underline [&_a:hover]:no-underline [&_a]:break-all",
  // inline + block code (block code is overridden by MARKDOWN_COMPONENTS.pre)
  "[&_code]:rounded [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-xs [&_code]:font-mono",
  "[&_pre]:rounded [&_pre]:bg-muted [&_pre]:p-3 [&_pre]:overflow-x-auto [&_pre_code]:bg-transparent [&_pre_code]:p-0",
  // headings
  "[&_h1]:text-lg [&_h1]:font-semibold [&_h1]:mt-4 [&_h1]:mb-2",
  "[&_h2]:text-base [&_h2]:font-semibold [&_h2]:mt-4 [&_h2]:mb-2",
  "[&_h3]:text-sm [&_h3]:font-semibold [&_h3]:mt-3 [&_h3]:mb-1.5",
  // paragraphs and lists (loose-list <p> margins zeroed to avoid double gaps)
  "[&_p]:my-0",
  "[&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5",
  "[&_ol]:my-2 [&_ol]:list-decimal [&_ol]:pl-5",
  "[&_li]:my-1 [&_li>p]:my-0",
  "[&_li>ul]:mt-1 [&_li>ol]:mt-1 [&_ul_ul]:list-[circle] [&_ol_ul]:list-[circle]",
  // blockquote
  "[&_blockquote]:border-l-2 [&_blockquote]:border-muted-foreground/30 [&_blockquote]:pl-3 [&_blockquote]:text-muted-foreground",
  // tables
  "[&_table]:w-full [&_table]:border-collapse [&_table]:my-2",
  "[&_th]:border [&_th]:px-2 [&_th]:py-1 [&_th]:text-left [&_th]:bg-muted/50",
  "[&_td]:border [&_td]:px-2 [&_td]:py-1",
  "[&_hr]:my-3",
].join(" ");

export interface MarkdownContentProps {
  content: string;
  className?: string;
  /** Show this when content trims to empty. Defaults to a muted em-dash. */
  emptyFallback?: React.ReactNode;
  /**
   * If true, preserve user-typed newlines via `whitespace-pre-wrap`. Set true
   * for raw chat messages where users may rely on hard line breaks; leave
   * false for AI/markdown content that already encodes structure.
   */
  preserveWhitespace?: boolean;
}

export function MarkdownContent({
  content,
  className,
  emptyFallback,
  preserveWhitespace = false,
}: MarkdownContentProps) {
  const raw = content.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim();
  if (!raw) {
    return (
      <span className="text-muted-foreground">{emptyFallback ?? "—"}</span>
    );
  }
  return (
    <div className={cn(BASE_CLASSES, preserveWhitespace && "whitespace-pre-wrap", className)}>
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={MARKDOWN_COMPONENTS}>
        {raw}
      </ReactMarkdown>
    </div>
  );
}
